### PR TITLE
Removes docker image after pushing.

### PR DESCRIPTION
**Pull request by stephanh**

### CODE REVIEW

**Comment by wrouesnel** [comment]
This would fail if there's enough of a time lag between the image being pushed and mesos spawning a job with it on the same host (and would show up as an intermittent build failure).

I'm also not sure that deleting an image in docker actually cleans up the intermediate images, which are a bigger problem as those will be persisted on `docker build` failures by default (and be way more images to manage).

Realistically we need a general `docker gc` solution (and people have created a few of them) that'll work for all cases, since *when* to GC a node is a function of disk IOPS utilization and disk space utilization i.e. it should be some job you schedule onto a node when certain criteria are met.

**Comment by stephanh** [comment]
True, in order to hit the race condition one would have to pull the image down before the build has finished, in particular, before even the `dockermake` command has finished. Under what circumstances do you think that will happen?

I agree with you that we need more. In particular, I think we need much better isolation around our CI. Nonetheless, we might as well do the right thing and clean up after ourselves as much as we can/is reasonable.

**Comment by stephanh** [comment]
@wrouesnel thoughts?

**Comment by wrouesnel** [comment]
I can't think of any specific reasons it would be a problem, since the timestamp pretty much ensures that even clicking "restart" will yield a different result. So other then a vague sense of distruct from PR isolation - :shipit:

**Pull request merged**
