### PR TITLE
Adds CI tooling principles.

### PR DESCRIPTION
**Pull request by stephanh**
I have created a set of principles that I think distills the way we have been thinking about writing our CI scripts currently.

### CODE REVIEW

**Comment by wrouesnel** [comment]
:shipit:

**Comment by lynnju** [comment]
:shipit:

**Comment by lvenegas** [comment]
:shipit:

**Comment by vineethvarghese** [comment]
I imagine this is tied to the way we deploy and publish - teamcity vs travis?

**Comment by stephanh** [comment]
@vineethvarghese Right now this repo only supports drone and travis. However, the principals could and should also apply to teamcity.

**Comment by vineethvarghese** [comment]
👍

**Comment by pdericson** [comment]
:+1:

**Pull request merged**
