### PR TITLE
Adds generic setup version script

### PR DESCRIPTION
**Pull request by stephanh**
This script takes a SEMVER version in `VERSION` and replaces it with the SEMVER version plus the commit hash, date and on non master branches the PR or branch name.

### CODE REVIEW

**Comment by wrouesnel** [comment]
This looks good, it should be merged ASAP.

**Comment by wrouesnel** [comment]
get_version should be made available as a shell library, rather than integrated into the script.

**Comment by stephanh** [comment]
I liked your previous comment better :smile:.

Based on our discussion do you still think it should be a shell library?

**Comment by wrouesnel** [comment]
I've forked the repo and added dockerbuild + a new version of the setup-version script. Will create a separate PR once I'm sure it's working properly.

**Comment by wrouesnel** [comment]
See #22

**Comment by stephanh** [comment]
Superseded by #22.

**Pull request closed without merging**
