### PR TITLE
Add generic commands that let us run stuff conditionally

### PR DESCRIPTION
**Pull request by triggerNZ**
Basically there are cases where we want different CI behaviour depending on whether we are a release branch or not. These scripts do that in a generalised way so you can execute any command conditionally

### CODE REVIEW

**Comment by stephanh** [comment]
@triggerNZ see https://github.com/CommBank/ci/blob/master/ci-release.bsh.This handles the on-release part already.

**Comment by triggerNZ** [comment]
@stephanh ah very cool! How do you feel about me adding a flag to invert its' behaviour? Or add an equivalent ci-nonrelease?

**Comment by triggerNZ** [comment]
Closing this in favour of adding a non-release equivalent of ci-release.bsh

**Comment by stephanh** [comment]
@triggerNZ I feel very good about that :smile:

**Pull request closed without merging**
