### PR TITLE
Use ARTIFACTORY_USER, defaulting to omnia-ci

### PR DESCRIPTION
**Pull request by rowandavies**
This allows the use of individual squad ci users on artifactory, instead of always omnia-ci.

### CODE REVIEW

**Comment by jsok** [comment]
@stephanh do you have any insight into why the sbt build docs tests would be unable to find the `./sbt` script?

**Comment by andynygard** [comment]
Looks like `../../sbt-ci-build-doc.bsh: line 86: sbt: command not found` first occurred in build 300 ([builds](https://travis-ci.org/CommBank/ci/builds)), which was a documentation-only change.

So it seems the problem must lie with a changed dependency or build environment.

**Comment by jsok** [comment]
I noticed that one of the gems this build relied on go updated just after June 30 which approx. corresponds with when the builds started failing, hence why I pinned them to specific versions. However that doesn't seem to be the root cause.

**Comment by vineethvarghese** [comment]
We shouldn't be using a mix of ci1 and ci2. Given that we are moving to
ci2, I would suggest we spend our efforts adding missing functionality to
ci2.

**Comment by rowandavies** [comment]
Closing this, since we are swapping to ci2, and we recommend others do the same since the build for ci seems to have broken somehow.

**Pull request closed without merging**
