### PR TITLE
Adding note about network issue with the travis ci

### PR DESCRIPTION
**Pull request by vineethvarghese**

### CODE REVIEW

**Comment by stephanh** [comment]
:+1:

**Comment by shmookey** [comment]
What's the workaround? Use wifi? Tether to own device? Might be worth mentioning.

**Comment by vineethvarghese** [comment]
I used my 4g but i felt it is best to just say the tool is a pain in the
office network and leave it users.

**Comment by shmookey** [comment]
Sure :+1:

**Comment by vineethvarghese** [comment]
Actually our wifi is also a pain. I will include this in the readme.

**Pull request merged**
